# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee00861b9381bf2dcc08006ee6b5ebb6f642e66bc712c8c6f92e28f6af2c460d3d7d6bd07fca787f6a28afa0532e46517a157c171699c8edda78d8d735f1b23f

test:
  secret_key_base: 1325f1dd621a55abccb0fbe08307d88f8a16c7ca149a19ddccd9d7408dbf3d085773d3bccc8a22802e8d1bc9ce874fffe417c39c9f74d30b93da5a9dee0936ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
